steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Authorize Cloud Build'
  entrypoint: 'bash'
  args:
    - -c
    - |
      apt-get install dnsutils -y &&
      cloudbuild_external_ip=$(dig @resolver4.opendns.com myip.opendns.com +short) &&
      gcloud container clusters update us-central-1 --zone=us-central1  --master-authorized-networks $cloudbuild_external_ip/32 &&
      echo $cloudbuild_external_ip
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'pods']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=us-central-1'
#options:
#  pool:
#    name: 'projects/upbeat-agent-389803/locations/us-central1/workerPools/private-pool'
    
